[package]
name = "my_stockfigher_trades_exec_crate"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[dependencies]
hyper = "0.7"
serde = "0.6"
serde_json = "0.6"
serde_macros = "0.6"
time = "0.1"
